# Generated by Django 2.2 on 2023-09-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdata',
            name='generator_p',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='generator_q',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='init_ang',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='init_volt',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='load_p',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='load_q',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='q_max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='q_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='faultcondition',
            name='is_bus_fault',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faultcondition',
            name='is_load_effect',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faultcondition',
            name='is_shunt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='R',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='X',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='Xn',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='half_B',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='negative_R',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='negative_X',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='zero_R',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='zero_X',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='zero_half_B',
            field=models.FloatField(default=0),
        ),
    ]
