# Generated by Django 2.2 on 2023-09-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20230909_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultcondition',
            name='fault_bus',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='faultcondition',
            name='fault_line_1',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='faultcondition',
            name='fault_line_2',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='faultcondition',
            name='line_percentage',
            field=models.SmallIntegerField(null=True),
        ),
    ]
