# Generated by Django 2.2 on 2023-09-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_auto_20230909_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busdata',
            name='bus_type',
        ),
        migrations.RemoveField(
            model_name='busdata',
            name='generator_p',
        ),
        migrations.RemoveField(
            model_name='busdata',
            name='generator_q',
        ),
        migrations.RemoveField(
            model_name='busdata',
            name='init_ang',
        ),
        migrations.RemoveField(
            model_name='busdata',
            name='init_volt',
        ),
        migrations.RemoveField(
            model_name='busdata',
            name='load_p',
        ),
        migrations.RemoveField(
            model_name='busdata',
            name='load_q',
        ),
        migrations.RemoveField(
            model_name='busdata',
            name='q_max',
        ),
        migrations.RemoveField(
            model_name='busdata',
            name='q_min',
        ),
    ]
