# Generated by Django 2.2 on 2023-09-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20230910_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linedata',
            name='R',
        ),
        migrations.RemoveField(
            model_name='linedata',
            name='X',
        ),
        migrations.RemoveField(
            model_name='linedata',
            name='Xn',
        ),
        migrations.RemoveField(
            model_name='linedata',
            name='half_B',
        ),
        migrations.RemoveField(
            model_name='linedata',
            name='line_type',
        ),
        migrations.RemoveField(
            model_name='linedata',
            name='negative_R',
        ),
        migrations.RemoveField(
            model_name='linedata',
            name='negative_X',
        ),
        migrations.RemoveField(
            model_name='linedata',
            name='zero_R',
        ),
        migrations.RemoveField(
            model_name='linedata',
            name='zero_X',
        ),
        migrations.RemoveField(
            model_name='linedata',
            name='zero_half_B',
        ),
    ]
