# Generated by Django 2.2 on 2023-09-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_excelfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelFile',
        ),
    ]
