# Generated by Django 2.2 on 2023-09-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_excelfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='find_file',
            field=models.BooleanField(default=False),
        ),
    ]
