# Generated by Django 2.2 on 2023-09-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_faultbusdata_faultlinedata_otherfaulti_otherfaultv_threefaulti_threefaultv'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultcondition',
            name='to_find',
            field=models.BooleanField(default=False),
        ),
    ]
