# Generated by Django 2.2 on 2023-09-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0011_faultcondition_to_find'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faultbusdata',
            old_name='Angle_Degree',
            new_name='Voltage_Deg',
        ),
    ]
