# Generated by Django 2.2 on 2023-09-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0015_auto_20230913_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
