# Generated by Django 2.2 on 2023-09-14 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0016_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='testzbus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='testzbuscolumn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contents', models.FloatField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.testzbus')),
            ],
        ),
    ]
