# Generated by Django 2.2 on 2023-09-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0019_auto_20230914_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaultCondition',
        ),
    ]
