# Generated by Django 2.2 on 2023-09-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0021_conditioncheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditioncheck',
            name='find_con',
            field=models.BooleanField(default=False),
        ),
    ]
