# Generated by Django 2.2 on 2023-09-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0022_conditioncheck_find_con'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basemva', models.SmallIntegerField()),
                ('is_flow', models.BooleanField()),
                ('fault_type', models.SmallIntegerField()),
                ('is_bus_fault', models.BooleanField(default=True)),
                ('fault_bus', models.SmallIntegerField(null=True)),
                ('fault_line_1', models.SmallIntegerField(null=True)),
                ('fault_line_2', models.SmallIntegerField(null=True)),
                ('line_percentage', models.SmallIntegerField(null=True)),
                ('impedence_R', models.FloatField()),
                ('impedence_X', models.FloatField()),
                ('is_shunt', models.BooleanField(default=False)),
                ('is_load_effect', models.BooleanField(default=False)),
                ('to_find', models.BooleanField(default=False)),
            ],
        ),
    ]
