# Generated by Django 2.2 on 2023-09-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0024_threezbus_threezbussource'),
    ]

    operations = [
        migrations.AddField(
            model_name='threezbus',
            name='check',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='threezbus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
