# Generated by Django 2.2 on 2023-09-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0025_auto_20230917_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherZbus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='zeroZbusSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.FloatField()),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.OtherZbus')),
            ],
        ),
        migrations.CreateModel(
            name='OtherZbusSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.FloatField()),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.OtherZbus')),
            ],
        ),
        migrations.CreateModel(
            name='negativeZbusSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.FloatField()),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.OtherZbus')),
            ],
        ),
    ]
