# Generated by Django 2.2 on 2023-09-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0026_negativezbussource_otherzbus_otherzbussource_zerozbussource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negativezbussource',
            name='source',
        ),
        migrations.RemoveField(
            model_name='otherzbussource',
            name='source',
        ),
        migrations.RemoveField(
            model_name='threezbussource',
            name='source',
        ),
        migrations.RemoveField(
            model_name='zerozbussource',
            name='source',
        ),
        migrations.AddField(
            model_name='negativezbussource',
            name='imag_source',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='negativezbussource',
            name='real_source',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='otherzbussource',
            name='imag_source',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='otherzbussource',
            name='real_source',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='threezbussource',
            name='img_source',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='threezbussource',
            name='real_source',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zerozbussource',
            name='imag_source',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zerozbussource',
            name='real_source',
            field=models.FloatField(default=0),
        ),
    ]
