# Generated by Django 2.2 on 2023-09-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0030_auto_20230919_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='negativezbussource',
            name='y_imag_source',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='negativezbussource',
            name='y_real_source',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='otherzbussource',
            name='y_imag_source',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='otherzbussource',
            name='y_real_source',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='threezbussource',
            name='y_imag_source',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='threezbussource',
            name='y_real_source',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zerozbussource',
            name='y_imag_source',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zerozbussource',
            name='y_real_source',
            field=models.FloatField(default=0),
        ),
    ]
