# Generated by Django 2.2 on 2023-09-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0031_auto_20230921_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='OthersequenceI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_Bus', models.SmallIntegerField()),
                ('To_Bus', models.SmallIntegerField()),
                ('Phase_A_Mag', models.FloatField()),
                ('Phase_A_Deg', models.FloatField()),
                ('Phase_B_Mag', models.FloatField()),
                ('Phase_B_Deg', models.FloatField()),
                ('Phase_C_Mag', models.FloatField()),
                ('Phase_C_Deg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OthersequenceV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_No', models.SmallIntegerField()),
                ('Phase_A_Mag', models.FloatField()),
                ('Phase_A_Deg', models.FloatField()),
                ('Phase_B_Mag', models.FloatField()),
                ('Phase_B_Deg', models.FloatField()),
                ('Phase_C_Mag', models.FloatField()),
                ('Phase_C_Deg', models.FloatField()),
            ],
        ),
    ]
