# Generated by Django 2.2 on 2023-09-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0033_auto_20230922_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afterflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_No', models.SmallIntegerField()),
                ('Voltage_Mag', models.FloatField(default=0)),
                ('Voltage_Deg', models.FloatField(default=0)),
                ('Generator_MW', models.FloatField(blank=True, default=0, null=True)),
                ('Generator_Mvar', models.FloatField(blank=True, default=0, null=True)),
                ('Load_MW', models.FloatField(blank=True, default=0, null=True)),
                ('Load_Mvar', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
