# Generated by Django 2.2 on 2023-09-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0034_afterflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliderbus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_No', models.SmallIntegerField()),
                ('Voltage_Mag', models.FloatField(default=0)),
                ('Voltage_Deg', models.FloatField(default=0)),
                ('Generator_MW', models.FloatField(blank=True, default=0, null=True)),
                ('Generator_Mvar', models.FloatField(blank=True, default=0, null=True)),
                ('Load_MW', models.FloatField(blank=True, default=0, null=True)),
                ('Load_Mvar', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SliderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_bus', models.SmallIntegerField()),
                ('To_bus', models.SmallIntegerField()),
                ('R', models.FloatField(default=0)),
                ('X', models.FloatField(default=0)),
                ('half_B', models.FloatField(default=0)),
                ('negative_R', models.FloatField(blank=True, default=0, null=True)),
                ('negative_X', models.FloatField(blank=True, default=0, null=True)),
                ('zero_R', models.FloatField(blank=True, default=0, null=True)),
                ('zero_X', models.FloatField(blank=True, default=0, null=True)),
                ('Xn', models.FloatField(blank=True, default=0, null=True)),
                ('zero_half_B', models.FloatField(blank=True, default=0, null=True)),
                ('line_type', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='afterflow',
            name='Generator_MW',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='afterflow',
            name='Generator_Mvar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='afterflow',
            name='Load_MW',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='afterflow',
            name='Load_Mvar',
            field=models.FloatField(default=0),
        ),
    ]
