# Generated by Django 2.2 on 2023-09-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0035_auto_20230923_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faultbusdata',
            name='Bus_Code',
        ),
    ]
