# Generated by Django 2.2 on 2023-09-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0036_remove_faultbusdata_bus_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(blank=True, upload_to='result')),
            ],
        ),
    ]
