# Generated by Django 2.2 on 2023-09-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0037_resultfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resultFile',
        ),
    ]
