# Generated by Django 2.2 on 2023-09-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0039_resultfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultfile',
            name='find_file',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
