# Generated by Django 2.2 on 2023-09-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0040_resultfile_find_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faultlinedata',
            old_name='half_B',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='faultlinedata',
            old_name='zero_half_B',
            new_name='zero_B',
        ),
        migrations.RenameField(
            model_name='linedata',
            old_name='half_B',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='linedata',
            old_name='zero_half_B',
            new_name='zero_B',
        ),
        migrations.RenameField(
            model_name='sliderline',
            old_name='half_B',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='sliderline',
            old_name='zero_half_B',
            new_name='zero_B',
        ),
    ]
