# Generated by Django 2.2 on 2023-10-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0042_errorcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultlinedata',
            name='line_type',
            field=models.SmallIntegerField(default=0),
        ),
    ]
