# Generated by Django 2.2 on 2023-10-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0043_faultlinedata_line_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherfaulti',
            name='line_type',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='othersequencei',
            name='line_type',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='threefaulti',
            name='line_type',
            field=models.SmallIntegerField(default=0),
        ),
    ]
